# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-ekm
canonical: http://fhir.ch/ig/ch-ekm
name: CH_EKM
title: "CH EKM (R4)"
description: FHIRÂ® Implementation Guide for the Electronic Clinical Report (Elektronische klinische Meldung) of the Swiss Federal Office of Public Health
status: draft # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2026-01-27
version: 0.0.1 
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build  # ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Federal Office of Public Health FOPH
contact:
  - name: Federal Office of Public Health FOPH
    telecom:
      - system: url
        value: https://www.bag.admin.ch/bag/en/home/das-bag/kontakt-standort.html

dependencies:
 ch.fhir.ig.ch-term: 3.3.x
 ch.fhir.ig.ch-core: 6.0.0
 ch.fhir.ig.ch-lab-report: 2.0.0
pages:
  index.md:
    title: Home


menu:
  Home: index.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  allow-extensible-warnings: true
  display-warnings: true
  path-resource:
    - input/resources
    - fsh-generated/resources
#  no-narrative: 
#    - Bundle/*
#  special-url:
#    - urn:oid:2.16.840.1.113883.6.316
  pin-canonicals: pin-multiples  
  excludettl: true
#  apply-version: false
#  default-version: true

instanceOptions:
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile. Options are:
  # - always: Set meta.profile for all Instances of profiles (default)
  # - never: Do not set meta.profile on any Instances
  # - inline-only: Set meta.profile for only Instances of profiles with Usage set to #inline
  # - standalone-only: Set meta.profile for only Instances of profiles where Usage is any value other than #inline
  setMetaProfile: never

